### ISSUE TITLE
InvalidCastException when generating source (since 2.0.3)

### ISSUE THREAD

**Issue by jhartmann123** [koenbeuk/EntityFrameworkCore.Projectables#16]
When I updated to `2.1.0` the following message started to appear when compiling:

```
Warning	CS8785
    Generator 'ProjectionExpressionGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. 
    Exception was of type 'InvalidCastException' with message 'Unable to cast object of type 'Microsoft.CodeAnalysis.CSharp.Syntax.MemberAccessExpressionSyntax' to type 'Microsoft.CodeAnalysis.CSharp.Syntax.SimpleNameSyntax'.'
```

Attached is a repro. It still works with 2.0.2. Starting with 2.0.3 this message appears.

[Projectables.Repro.zip](https://github.com/koenbeuk/EntityFrameworkCore.Projectables/files/7840263/Projectables.Repro.zip)

**Comment by koenbeuk** [comment]
Thanks for brining this up and thanks for the repro!

This indeed is a regression since 2.0.2 and it affects named types (Enums, static classes, ....). A fix will be merged shortly
