### ISSUE TITLE
InvalidCastException when expression contains a class cast

### ISSUE THREAD

**Issue by jhartmann123** [koenbeuk/EntityFrameworkCore.Projectables#18]
When an expression contains a class cast of a property the following warning appears when compiling. This is after updating to 2.1.1 which fixed #16.  

```
Warning	CS8785
    Generator 'ProjectionExpressionGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result.
    Exception was of type 'InvalidCastException' with message 'Unable to cast object of type 'Microsoft.CodeAnalysis.CSharp.Syntax.MemberAccessExpressionSyntax' to type 'Microsoft.CodeAnalysis.CSharp.Syntax.SimpleNameSyntax'.'
```

Example: `x => new Result { Description = ((OtherEntity)x).Description }`

The expression works in 2.0.2.

Repro: [Projectables.Repro.zip](https://github.com/koenbeuk/EntityFrameworkCore.Projectables/files/7897265/Projectables.Repro.zip)

**Comment by koenbeuk** [comment]
Thanks for the report and the repro again, this is very much appreciated!

I have an upcoming fix however I'd like to add some more tests so expect a merge within the next few days.

We should consider a general rewrite of the `ExpressionSyntaxRewriter` as its currently in a bad state. I may open up an additional issue for that.
